export const LoginSuccessfuL="Login Successfully"
export const InvalidInput="Invalid Input"
export const GotoSignUp="Swipe Down to login again OR Click Ok to go to SignUp"
export const EmailPassIncorrect="email and password incorrect"
export const PhonePassIncorrect="Phon Number and password incorrect"
export const SomethingWrong="Something Wrong"
export const FormSuccessfuL="Form Submit Successfully"
export const GoToHome="Check Car Datails"
export const PermissionToAccess='Permission to access camera roll is required!'
export const NoItems="No Items in Favourites";
export const Itemadded="Item has been added";
export const Itemremoved='Item has been removed';