export const LoginSuccessfuL="Login Successfully"
export const InvalidInput="Invalid Input"
export const GotoSignUp="Swipe Down to login again OR Click Ok to go to SignUp"
export const EmailPassIncorrect="email and password incorrect"
export const PhonePassIncorrect="Phon Number and password incorrect"
export const SomethingWrong="Something Wrong"
export const FormSuccessfuL="Form Submit Successfully"
export const GoToHome="Go to home"
export const PermissionToAccess='Permission to access camera roll is required!'
