import { COLOR } from "../../Theme/Colors";

export const DreamCar="Your Next Dream Car";
export const Results="1005 results in Islamabad ";
export const date="11 June";
export const KiloMeter="2010,  4556Km";
export const Products=[
    {
        id:1,
        src:require('../../../assets/images/carlist/img1.png'),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "like",
        date:"11 June",
        location:"Islamabad"
    },
    {
        id:2,
        src:require('../../../assets/images/carlist/img2.png'),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "like",
        date:"11 June",
        location:"Islamabad"
    },
    {
        id:3,
        src:require("../../../assets/images/carlist/img3.png"),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "like",
        date:"11 June",
        location:"Islamabad"
    },
    {
        id:4,
        src:require("../../../assets/images/carlist/img4.png"),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "like",
        date:"11 June",
        location:"Islamabad"
    },
    {
        id:5,
        src:require("../../../assets/images/carlist/img5.png"),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "like",
        date:"11 June",
        location:"Islamabad"
    },
]


export const orderList=[
    {
        id:1,
        src:require('../../../assets/images/carlist/img1.png'),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "Payed",
        date:"11 June",
        location:"Islamabad"
    },
    {
        id:2,
        src:require('../../../assets/images/carlist/img2.png'),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "Pending",
        date:"11 June",
        location:"Islamabad"
    },
    {
        id:3,
        src:require("../../../assets/images/carlist/img3.png"),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "Pending",
        date:"11 June",
        location:"Islamabad"
    },
    {
        id:4,
        src:require("../../../assets/images/carlist/img4.png"),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "Pending",
        date:"11 June",
        location:"Islamabad"
    },
    {
        id:5,
        src:require("../../../assets/images/carlist/img5.png"),
        Price:"Rs. 50 lakh ",
        Title:"Toyota Yaris iA",
        year:"2010,",
        KMeter:" 4556Km",
        status: "Payed",
        date:"11 June",
        location:"Islamabad"
    },
]
export const chatList=[
    {
        id:1,
        src:require('../../../assets/images/carlist/img1.png'),
        color:COLOR.Maize,
        User:"Alice Smith",
        Msg:"Great. I will have a look",
        Audio:"Sent a voice message",
        status: "msg",
        Time:"4:20 PM",
        attach:"Sent an attachment",
        count:"3",
        seen:true,
        Incoming:true,
    },
    {
        id:2,
        src:require('../../../assets/images/carlist/img1.png'),
        color:COLOR.SunsetOrange,
        User:"Alice Smith",
        Msg:"Great. I will have a look",
        Audio:"Sent a voice message",
        status: "audio",
        Time:"4:20 PM",
        attach:"Sent an attachment",
        count:"3",
        seen:false,
        Incoming:false,
    },
    {
        id:3,
        src:require('../../../assets/images/carlist/img4.png'),
        color:COLOR.Maize,
        User:"Alice Smith",
        Msg:"Great. I will have a look",
        Audio:"Sent a voice message",
        status: "msg",
        Time:"4:20 PM",
        attach:"Sent an attachment",
        count:"1",
        seen:true,
        Incoming:true,
    },
    {   id:4,
        src:require('../../../assets/images/carlist/img2.png'),
        color:COLOR.Eucalyptus,
        User:"Alice Smith",
        Msg:"Great. I will have a look",
        Audio:"Sent a voice message",
        status: "attach",
        Time:"4:20 PM",
        attach:"Sent an attachment",
        count:"4",
        seen:true,
        Incoming:true,
    },
    {
        id:5,
        src:require('../../../assets/images/carlist/img3.png'),
        color:COLOR.SunsetOrange,
        User:"Alice Smith",
        Msg:"Great. I will have a look",
        Audio:"Sent a voice message",
        status: "Payed",
        Time:"4:20 PM",
        attach:"Sent an attachment",
        count:"3",
        seen:false,
        Incoming:false,
    },
    {   id:6,
        src:require('../../../assets/images/carlist/img2.png'),
        color:COLOR.Eucalyptus,
        User:"Alice Smith",
        Msg:"Great. I will have a look",
        Audio:"Sent a voice message",
        status: "attach",
        Time:"4:20 PM",
        attach:"Sent an attachment",
        count:"2",
        seen:true,
        Incoming:true,
    },
    {
        id:7,
        src:require('../../../assets/images/carlist/img3.png'),
        color:COLOR.Maize,
        User:"Alice Smith",
        Msg:"Great. I will have a look",
        Audio:"Sent a voice message",
        status: "Payed",
        Time:"4:20 PM",
        attach:"Sent an attachment",
        count:"3",
        seen:false,
        Incoming:false,
    },
]