export const discountText = "Pay 10% Token Amount"
export const payPriceText = "Rs. 50 lakh "
export const paiedLocation = "Islamabad "
export const payNowButton = "Pay Now"
export const payChatButton = "Chat With Seller"
