export const ListData=[
    { id: '1', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '2', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '3', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '4', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '5', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '6', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '7', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '8', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '9', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '10', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '11', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '12', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
    { id: '13', name: "Application name", time: "now", userName: 'Hi Anastassia!' },
];